# This is a basic workflow to help you get started with actions

name: Cd
 on:
  push:
    branches:
    - main
    - release/*
 on:
  pull_request:
    branches:
    - main
    on:
  schedule:
  - cron: "0 2 * * 1-5"
  on:
  workflow_dispatch:
 build:
 jobs:
  my_job:
    name: deploy to staging
    runs-on:windows-latest
 - name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
 setups:
 - uses: actions/checkup@v2
 - name: set up python 3.8
 - uses: actions/setup-python@v1
 with:
   python-version: 3.8
 - name: install dependencies
   run:
   make install
 - name: Install Dependencies
  run: npm install
  steps:
- run: npm publish
  if: github.event_name == 'push'
